const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const slides = ['slide1', 'slide2', 'slide3', 'slide4'];
const ids = ['home', 'her-story', 'dream-world', 'sweet-moments'];
const titles = ['Birthday Opening', 'Her Story', 'Dream World', 'Sweet Moments'];
const navigation = fs.readFileSync(path.join(root, 'shared/navigation.html'), 'utf8');
function section(slide, prefix) {
  return fs.readFileSync(path.join(root, 'slides', slide, 'section.html'), 'utf8')
    .replace('{{navigation}}', navigation)
    .replaceAll('{{assets}}', `${prefix}slides/${slide}/assets/`)
    .replaceAll('{{root}}', prefix);
}
function document(title, selected, prefix) {
  const skipId = selected.length > 1 ? 'her-story' : ids[slides.indexOf(selected[0])];
  return `<!doctype html>
<!-- Generated by build.cjs. Edit slides/slideN/section.html instead. -->
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#73b5ec">
  <meta name="description" content="A birthday journey through her stories, a kinder dream world, and sweet moments together.">
  <title>${title} — Birthday Blooms</title>
  <link rel="icon" type="image/svg+xml" href="${prefix}shared/favicon.svg">
  <link rel="stylesheet" href="${prefix}shared/base.css">
  ${selected.map(slide => `<link rel="stylesheet" href="${prefix}slides/${slide}/${slide}.css">`).join('\n  ')}
  <script type="module" src="${prefix}shared/app.js"></script>
</head><body>
  <a class="skip-link" href="#${skipId}">Skip to content</a>
  <main>${selected.map(slide => section(slide, prefix)).join('\n')}</main>
  <nav class="slide-controls" aria-label="Slide navigation"><button type="button" data-slide-prev aria-label="Previous slide">‹</button><span data-slide-position aria-live="polite"></span><button type="button" data-slide-next aria-label="Next slide">›</button></nav>
  <button class="motion-control" type="button" data-motion aria-pressed="false">Pause motion</button>
</body></html>\n`;
}
fs.writeFileSync(path.join(root, 'index.html'), document('A Journey for You', slides, ''));
slides.forEach((slide, index) => fs.writeFileSync(path.join(root, 'slides', slide, 'index.html'), document(titles[index], [slide], '../../')));
console.log('Built main website and four standalone slides from their templates.');

